var date = new Date()
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toLocaleDateString())
console.log(date.getFullYear())
console.log(date.getDate())
console.log(date.getMilliseconds())